### ISSUE TITLE
Na geração de NFC-e não está sendo utilizado a descrição do produto

### ISSUE THREAD

**Issue by tomaslmz** [Alexssmusica/node-pdf-nfe#1]
Ao gerar uma NFC-e, todos os produtos possuem a mesma descrição: "NOTA FISCAL EMITIDA EM AMB"

**Comment by Alexssmusica** [comment]
Boa tarde, o xml gerado foi feito no mod 2 em homologação?

**Comment by tomaslmz** [comment]
> Boa tarde, o xml gerado foi feito no mod 2 em homologação?

Boa tarde! O xml gerado está com esse módulo e tipo de ambiente:
<mod>65</mod>
<tpAmb>1</tpAmb>

**Comment by Alexssmusica** [comment]
Certo já estou verificado o problema.

**Comment by Alexssmusica** [comment]
Já resolvi esta na versão 1.1.7

**Comment by Alexssmusica** [comment]
Você se quiser testar os xmls eu tenho um site gratuito https://danfenfeonline.com.br/gerar-danfe
